// <auto-generated />
namespace SMS_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createStudentTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createStudentTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202107190439216_createStudentTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
